version: "3.8"
services:
  postgres:
    image: postgres:15.1
    container_name: internal-prod-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - docker.env

  test-postgres:
    image: postgres:15.1
    container_name: test-db
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgadmin4_container
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - docker.env

  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: